services:
  postgres:
    image: postgres:18
    container_name: licita-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: licita_ai
      POSTGRES_USER: licita
      POSTGRES_PASSWORD: licita_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
