spring.application.name=LicitaAI

spring.datasource.url=jdbc:postgresql://localhost:5432/licita_ai
spring.datasource.username=licita
spring.datasource.password=licita_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
